# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 001bf1708be0eb7e813b3e12b19d753ea915fe1d0445c2bba0c563cf72148194ec1d2ae8073e9f107643f777fbb9357c47ea8f2699c74191e2978d8086eab117

test:
  secret_key_base: 529616c019659502b2b599dbba5acc6de3cf36c7279dbf6d549a3c27b16d153843a0d40f0732611b722b57794fe45f38c8aef6f5130c86041b2f9d97b39c8b6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
